version: '3'

services:
  mongo:
    image: drannoc/mongosail
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./db/logs/:/data/logs/
      - ./db/data/:/data/db
    ports:
      - 27017:27017
  oven:
    image: drannoc/oven
    ports:
      - "3031:3031"
    volumes:
      - ./output:/app/output
  bakery:
    image: drannoc/bakery
    ports:
      - "8082:8082"
