version: '3'

services:
  mongo:
    image: drannoc/mongosail
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./db/logs/:/data/logs/
      - ./db/data/:/data/db
      - ./scripts/mongo/migrations/:/migrations/
    ports:
      - 27017:27017
    networks:
      - panya_net
networks:
  panya_net:
    external: true